"""columm update1

Revision ID: 0177e054e813
Revises: 1de6fa2b1ba5
Create Date: 2025-08-10 23:18:20.337470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0177e054e813'
down_revision: Union[str, None] = '1de6fa2b1ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('example', sa.String(length=255), nullable=False))
    op.add_column('information', sa.Column('lesson_id', sa.Integer(), nullable=False))
    op.drop_constraint('information_ibfk_1', 'information', type_='foreignkey')
    op.create_foreign_key(None, 'information', 'lesson', ['lesson_id'], ['id'])
    op.drop_column('information', 'lessone_id')
    op.drop_column('information', 'examole')
    op.add_column('test', sa.Column('lesson_id', sa.Integer(), nullable=False))
    op.drop_constraint('test_ibfk_1', 'test', type_='foreignkey')
    op.create_foreign_key(None, 'test', 'lesson', ['lesson_id'], ['id'])
    op.drop_column('test', 'lessone_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('lessone_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.create_foreign_key('test_ibfk_1', 'test', 'lesson', ['lessone_id'], ['id'])
    op.drop_column('test', 'lesson_id')
    op.add_column('information', sa.Column('examole', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('information', sa.Column('lessone_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'information', type_='foreignkey')
    op.create_foreign_key('information_ibfk_1', 'information', 'lesson', ['lessone_id'], ['id'])
    op.drop_column('information', 'lesson_id')
    op.drop_column('information', 'example')
    # ### end Alembic commands ###
