"""lesson update

Revision ID: 1de6fa2b1ba5
Revises: 417a4e41d6f5
Create Date: 2025-08-10 22:57:20.626330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1de6fa2b1ba5'
down_revision: Union[str, None] = '417a4e41d6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('science_id', sa.Integer(), nullable=False))
    op.drop_constraint('lesson_ibfk_1', 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'science', ['science_id'], ['id'])
    op.drop_column('lesson', 'sciene_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('sciene_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.create_foreign_key('lesson_ibfk_1', 'lesson', 'science', ['sciene_id'], ['id'])
    op.drop_column('lesson', 'science_id')
    # ### end Alembic commands ###
